config/urls.py
from django.contrib import admin
from django.urls import path, include



from pybo.views import base_views
from demo.views import upload_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    
    path('demo/',include('demo.urls')),
]

handler404 = 'common.views.page_not_found'

demo/urls.py
from django.urls import path
from .views import upload_views,calculate_views


app_name = 'demo'

urlpatterns = [
    #upload_views.py 
    path('upload/', upload_views.upload_csv, name='upload_csv'),
    path('result/', calculate_views.show_analysis_result, name='result'),
]

demo/models.py
from django.db import models

# Create your models here.
class CSVData(models.Model):
    csv_info = models.FloatField(default=0.0)
    csv_file = models.FileField(upload_to='PPI/',null=True)

demo/forms.py
from django import forms
from demo.models import CSVData



class UploadForm(forms.Form):
    ppi_file = forms.FileField()

demo/views.py
from django.shortcuts import render
from django.views.generic.base import View

import csv 
from io import TextIOWrapper

from django.db import connection

from .forms import UploadForm
from demo.models import CSVData



def upload_csv(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_data = CSVData(csv_file=request.FILES['csv_file'])
            csv_data.save()
            return render(request, 'demo/success.html')
    else:
        form = UploadForm()
    return render(request, 'demo/upload.html', {'form': form})












# 데이터베이스 작업 수행
connection.close()  # 연결을 닫음

demo/views/calculate_views.py
import io
import numpy as np
from scipy.interpolate import CubicSpline
from scipy import signal
import scipy
import matplotlib.pyplot as plt

import os 
import base64
import re

from django.shortcuts import render
from django.views.generic.base import View


def read_dataset():
    files_path = 'media/PPI/'
    file_name_and_time_lst = []

    for f_name in os.listdir(f"{files_path}"):
        written_time = os.path.getctime(f"{files_path}{f_name}")
        file_name_and_time_lst.append((f_name, written_time))

    sorted_file_lst = sorted(file_name_and_time_lst, key=lambda x: x[1], reverse=True)

    if sorted_file_lst:  
        recent_file = sorted_file_lst[0]
        recent_file_name = recent_file[0]
        csv_dataset = os.path.join(files_path,recent_file_name)
    else:
        pass

    return csv_dataset


def dataset_IBI(data):
    if data.endswith('.csv'):
        data = np.genfromtxt(data, delimiter=',')
        data = np.nan_to_num(data, copy=False)

        IBI=[int(tmp)/128 for tmp in data]

    elif data.endswith('.txt'):
        with open(data, 'r') as file:
            data = file.read()

        # data = np.genfromtxt(io.StringIO(data), delimiter=',')
        data = re.split('; |, |\*|\n|\t', data)
        data = np.nan_to_num(data, copy=False)

        IBI=[int(tmp)/128 for tmp in data if tmp.isdigit()]
    else:
        raise ValueError("Unsupported file format. Supported formats: .csv and .txt")

   
    
    mIBI=sum(IBI)/len(IBI)
    if mIBI>400:
        IBI=[ibi/1000 for ibi in IBI]
    
    return IBI


def check_ms(IBI): 

    IBI=np.array(IBI)
    if np.mean(IBI)<400:
        IBI=np.round(IBI*1000)

    return IBI

def check_IBI(input):
    input=np.array(input)
    if input.shape[0]<10:
        return -1
    if np.all(input>2000):
        return -1
    if np.all(input<400):
        return -1
    if np.all(np.diff(input)<=0):
        return -1
    
    return input

def anal_HRVtime(IBI):
    IBI=dataset_IBI(IBI)
    IBI=check_ms(IBI)
    IBI=check_IBI(IBI)

    def calc_pNNx(dIBI, x=50):
        return 100*np.sum(np.abs(dIBI)>x)/dIBI.shape[0]
   
    IBI = np.array(IBI)
    dIBI = np.diff(IBI)
    
    AVNN = np.mean(IBI)
    SDSD = np.std(dIBI)
    RMSSD = np.sqrt(np.mean(dIBI*dIBI))
    pNNx = calc_pNNx(dIBI, x=50)
    
    return '{:.1f}'.format(AVNN), '{:.1f}'.format(SDSD), '{:.1f}'.format(RMSSD), '{:.1f}'.format(pNNx)

def anal_HRVfreq(IBI):

    IBI = dataset_IBI(IBI)

    IBI=check_ms(IBI)
    IBI=check_IBI(IBI)
    tonset=np.cumsum(IBI)

    # detrend
    IBI = signal.detrend(IBI)
    IBI = IBI - np.mean(IBI)

    # interpolation (1kHz)
    Fs_interp=1000
    cs = CubicSpline(tonset, IBI)
    tonset_interpolated = np.arange(tonset[0], tonset[-1], 1000/Fs_interp, dtype=int)
    IBI_interpolared=cs(tonset_interpolated)
    Fs_resamp=4
    IBI_resampled = signal.resample(IBI_interpolared, Fs_interp//Fs_resamp)
    
    # windowing (hanning)
    IBI_windowed=IBI_resampled*np.hanning(IBI_resampled.shape[0])
    
    # FFT 
    (freq, aY)=scipy.signal.welch(IBI_windowed, Fs_resamp, nperseg=len(IBI_windowed))  ##
        
    # Power Sum
    rangeVLF=[0.0033, 0.04]
    rangeLF=[0.04, 0.15]
    rangeHF=[0.15, 0.4]
    
    pTP=np.trapz(aY, freq)
    pVLF=np.trapz(aY[ (freq>=rangeVLF[0])&(freq>rangeVLF[1]) ], freq[ (freq>=rangeVLF[0])&(freq>rangeVLF[1]) ])
    pLF=np.trapz(aY[ (freq>=rangeLF[0])&(freq>rangeLF[1]) ], freq[ (freq>=rangeLF[0])&(freq>rangeLF[1]) ])
    pHF=np.trapz(aY[ (freq>=rangeHF[0])&(freq>rangeHF[1]) ], freq[ (freq>=rangeHF[0])&(freq>rangeHF[1]) ])
    
    pLF_HF=pLF/pHF
    nLF=pLF/(pTP-pVLF)
    nHF=pHF/(pTP-pVLF)
    return freq, aY, '{:.1f}'.format(pTP), '{:.1f}'.format(pVLF), '{:.1f}'.format(pLF), '{:.1f}'.format(pHF), '{:.1f}'.format(pLF_HF), '{:.1f}'.format(nLF), '{:.1f}'.format(nHF)



def show_analysis_result(request):
    dataset = read_dataset()
    avnn, sdsd, rmssd, pnnx = anal_HRVtime(dataset)
    freq, aY, ptp, pvlf, plf, phf, plf_hf, nlf, nhf = anal_HRVfreq(dataset)

    # Create and save the plot to a BytesIO object
    plt.switch_backend('Agg') 
    fig, ax = plt.subplots(figsize=(6, 4))
    plt.stem(freq, aY, 'b', markerfmt=" ", basefmt="-b")
    plt.ylabel('|Magnitude| (ms^2/Hz)')
    plt.xlabel('Frequency (Hz)')
    plt.tight_layout()

    # Save the plot to a BytesIO object
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    plt.close()

    # Embed the plot in the response
    data_uri = base64.b64encode(buf.read()).decode('utf-8')
    img_tag = f'<img src="data:image/png;base64,{data_uri}"/>'

    return render(request, 'demo/result.html', {
        'avnn_result': avnn,
        'sdsd_result': sdsd,
        'rmssd_result': rmssd,
        'pnnx_result': pnnx,
        'ptp_result': ptp,
        'pvlf_result': pvlf,
        'plf_result': plf,
        'phf_result': phf,
        'plf_hf_result': plf_hf,
        'nlf_result': nlf,
        'nhf_result': nhf,
        'plot': img_tag  # Include the plot in the response
    })

demo/views/upload_views.py
from django.shortcuts import render
from django.views.generic.base import View

import csv 
from io import TextIOWrapper

from django.db import connection

from ..forms import UploadForm
from demo.models import CSVData


def upload_csv(request):
    if request.method == 'POST':

        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            csv_data = CSVData(csv_file=request.FILES['ppi_file'])
            csv_data.save()

            return render(request, 'demo/success.html')
        
    else:
        form = UploadForm()
    return render(request, 'demo/upload.html', {'form': form})

templates/demo/result.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
    <title> Analysis Result</title>
</head>

<body>
    <h1 style="text-align: center;"><strong>HRV analysis tool</strong></h1>
    
    <div style="display: flex; justify-content: center;">
        <!-- Left Column -->
        <div style="margin: 100px; text-align: center;">
            <div>
                <h3>HRV Time Analysis Result</h3>
                <table>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                    <tr>
                        <td><strong>AVNN</strong></td>
                        <td>{{ avnn_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>SDSD</strong></td>
                        <td>{{ sdsd_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>RMSSD</strong></td>
                        <td>{{ rmssd_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>pNNx</strong></td>
                        <td>{{ pnnx_result }}</td>
                    </tr>
                </table>
            </div>
        </div>
    
        <!-- Right Column -->
        <div style="margin: 100px; text-align: center;">
            <div>
                <h3>HRV Frequency Analysis Result</h3>
                <table>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                    <tr>
                        <td><strong>pTP</strong></td>
                        <td>{{ ptp_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>pVLF</strong></td>
                        <td>{{ pvlf_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>pLF</strong></td>
                        <td>{{ plf_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>pHF</strong></td>
                        <td>{{ phf_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>pLF/HF</strong></td>
                        <td>{{ plf_hf_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>nLF</strong></td>
                        <td>{{ nlf_result }}</td>
                    </tr>
                    <tr>
                        <td><strong>nHF</strong></td>
                        <td>{{ nhf_result }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <!-- Below Left and Right Columns -->
    <div style="text-align: center; width: 80%; margin: 0 auto;">
        <p>{{ plot|safe }}</p>
    </div>
</body>


<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    th {
        background-color: #f2f2f2;
    }
</style>

</html>

{% endblock %}

templates/demo/success.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div>
    <title>Success</title>
    <h1 style="text-align: center;"><strong>HRV analysis tool</strong></h1>
    <h3 style="text-align: center;">Upload Successful</h3>

    <img src="{% static 'demo/loading_img.gif' %}" width="10%" height="10%" style="display: block; margin: 0 auto;">

    	
    <a style="text-align: center;" href="{% url 'demo:result' %}">View Results</a>
</div>


<script>
    // Automatically redirect after 1.5 seconds
    setTimeout(function() {
        window.location.href = "{% url 'demo:result' %}";
    }, 1000); // 1000 milliseconds (1 seconds)
</script>
{% endblock %}

templates/demo/test_HRV.html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
    <script defer src="https://pyscript.net/latest/pyscript.js"></script>

    <style>
      table {
        width: 640 px;
        border-top: 1px solid #444444;
        border-collapse: collapse;
      }
      th, td {
        border-bottom: 1px solid #444444;
        border-left: 1px solid #444444;
        padding: 2px;
      }
      th:first-child, td:first-child {
        border-left: none;
      }
</style>
  </head>

  <body> 
    <div style="background: white ; width: 640px">
    
      <h1>HRV analysis (V1.0)</h1>
      <p align="justify"> 
Heart Rate Variability (HRV) is a physiological phenomenon that refers to the variation in time intervals between successive heartbeats. It is a measure of the autonomic nervous system's influence on heart rate and is often used as a non-invasive marker of the body's ability to regulate and respond to various physiological and psychological stressors.
This program computes various HRV time domain variables, including AVNN, SDSD, RMSSD, and pNN50, as well as frequency domain variables such as TP, VLF, LF, HF, LF/HF, nLF, and nHF.

      </p>

      <input type="file" id="fileInput" accept=".txt, .csv">
      <div id="fileContent"></div>
      <script>
        document.getElementById('fileInput').addEventListener('change', function (e) {const file = e.target.files[0];
          if (!file) {
              alert('Choose a file.');
              return;
          }
          const reader = new FileReader();
          reader.onload = function (e) {
              fileContent = e.target.result;
              fname=file.name.split(".");
              fname.pop()
              fname=fname.join('.')
              //document.getElementById('fileContent').textContent = fileContent;
              run = pyscript.interpreter.globals.get('run_correction') 
              run(fileContent);
          };
          reader.readAsText(file);
        });

        
        function download(fileContent){
          const blob = new Blob([fileContent], { type: 'text/plain' });
          const a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = fname+'_corrected.csv';
          a.click();
          URL.revokeObjectURL(a.href);
        }

      </script>

      <div id="plot"></div>
      <div id="HRVresult"></div>
        <py-config type="toml">
          packages = ["numpy", "matplotlib", "scikit-learn", "scipy"]
          [[fetch]]
          files = ["py_ectopic_correction_web_v1.py", "py_anal_HRV.py"]
        </py-config>

        <py-script>
          import matplotlib.pyplot as plt
          import numpy as np
          import re
          import matplotlib.patches as mpatches
          from pyscript import Element

          from py_ectopic_correction_web_v1 import preproc, ectopic_correction, calc_PPI
          from py_anal_HRV import anal_HRVfreq, anal_HRVtime

          from js import download

          def run_correction(data):
            data=re.split('; |, |\*|\n|\t', data)
            IBI=[int(tmp)/128 for tmp in data if tmp.isdigit()]
            
            mIBI=sum(IBI)/len(IBI)
            if mIBI>400:
              IBI=[ibi/1000 for ibi in IBI]

            t_onset_0=np.cumsum(IBI)
            t_onset_1=t_onset_0.copy()

            t_onset, flag = ectopic_correction(t_onset_0)
            t_onset=t_onset[1:]
            
            PPI_0=calc_PPI(t_onset_0)
            PPI=calc_PPI(t_onset)
            
            ## DRAW
            '''
            fig, ax = plt.subplots()
            p1=plt.plot(t_onset_0[:-1], PPI_0, 'y', linewidth=5)
            #plt.plot(t_onset_1[:-1], PPI_1, 'r')
            p2=plt.plot(t_onset[:-1], PPI, 'k')
            plt.xlabel('Time (s)')
            plt.ylabel('interbeat interval (s)')
            
            # Legend
            yellowLine = mpatches.Patch(color='yellow', label='raw')
            blackLine = mpatches.Patch(color='black', label='corrected')
            plt.legend(handles=[yellowLine, blackLine])
            display(fig, target="plot")
            '''

            # HRV analysis
            AVNN, SDSD, RMSSD, pNNx=anal_HRVtime(IBI)
            freq, aY, TP, VLF, LF, HF, LF_HF, nLF, nHF=anal_HRVfreq(IBI)
            
            fig, ax = plt.subplots(figsize=(6,4))
            plt.stem(freq, aY, 'b', markerfmt=" ", basefmt="-b")
            plt.ylabel('|Magnitude| (ms^2/Hz)')
            plt.xlabel('Frequency (Hz)')
            plt.tight_layout()
            plt.show()

            display(fig, target="plot")

            ## Download
            sPPI=[str(ppi) for ppi in PPI]
            PPT_str=', '.join(sPPI)
            download(PPT_str)

            ## Display HRV result to table
            txtAVNN = Element("tAVNN")
            txtSDSD = Element("tSDSD")
            txtRMSSD = Element("tRMSSD")
            txtpNN50 = Element("tpNN50")

            txtAVNN.element.innerText = AVNN
            txtSDSD.element.innerText = SDSD
            txtRMSSD.element.innerText = RMSSD
            txtpNN50.element.innerText = pNNx

            xtTP = Element("tTP")
            txtVLF = Element("tVLF")
            txtLF = Element("tLF")
            txtHF = Element("tHF")
            txtLF_HF = Element("tLF_HF")
            txtnLF = Element("tnLF")
            txtnHF = Element("tnHF")

            xtTP.element.innerText = TP
            txtVLF.element.innerText = VLF
            txtLF.element.innerText = LF
            txtHF.element.innerText = HF
            txtLF_HF.element.innerText = LF_HF
            txtnLF.element.innerText = nLF
            txtnHF.element.innerText = nHF

        </py-script>
      </div> 

    <table border="0.1" width="640">
      <thead>
        <tr>
          <th>HRV variable</th>
          <th width>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>AVNN (ms)</td>
          <td id="tAVNN"></td>
        </tr>
        <tr>
          <td>SDSD (ms)</td>
          <td id="tSDSD"></td>
        </tr>
        <tr>
          <td>RMSSD (ms)</td>
          <td id="tRMSSD"></td>
        </tr>
        <tr>
          <td>pNN50 (%)</td>
          <td id="tpNN50"></td>
        </tr>
        <tr>
          <td>TP (ms^2)</td>
          <td id="tTP"></td>
        </tr>
        <tr>
          <td>VLF (ms^2)</td>
          <td id="tVLF"></td>
        </tr>
        <tr>
          <td>LF (ms^2)</td>
          <td id="tLF"></td>
        </tr>
        <tr>
          <td>HF (ms^2)</td>
          <td id="tHF"></td>
        </tr>
        <tr>
          <td>LF/HF (n.u.)</td>
          <td id="tLF_HF"></td>
        </tr>
        <tr>
          <td>nLF (n.u.)</td>
          <td id="tnLF"></td>
        </tr>
        <tr>
          <td>nHF (n.u.)</td>
          <td id="tnHF"></td>
        </tr>
      </tbody>
    </table>  

    <p align="justify" width=640 px>
      <font size=2 color='lightgray'>Copyright © 2023 Hangsik Shin (hangsik.shin@gmail.com), Asan Medical Center, University of Ulsan College of Medicine. All Rights Reserved
      </font>
    </p>
  </body>
</html>

templates/demo/upload.html
{% extends "base.html" %}

{% block content %}
<div class="header">
    <h1 style="text-align: center;"><strong>HRV analysis tool</strong></h1>
</div>
<div class="file-info"></div>
<form method="post" enctype="multipart/form-data" id="upload-form">
    {% csrf_token %}
    <div class="file-drop-container">
        <div class="file-drop">
            <label for="id_ppi_file">Drag and drop your PPI file(.csv or .txt) here</label><br>
            {{ form.ppi_file }}
        </div>
        <input type="submit" value="Upload" class="upload-button" id="upload-button">
    </div>
</form>

<div class="centered-divs">
    <div class="centered-text">
        This program computes various HRV time domain variables, including AVNN, SDSD, RMSSD, and pNN50, as well as
        frequency domain variables such as TP, VLF, LF, HF, LF/HF, nLF, and nHF.
    </div>

    <div class="centered-text">
        Heart Rate Variability (HRV) is a physiological phenomenon that refers to the variation in time intervals
        between successive heartbeats.<br> It is a measure of the autonomic nervous system's influence on heart rate and is often used as a non-invasive marker of the body's ability to regulate and respond to various physiological and psychological stressors.
    </div>
</div>

<style>
    .header {
        text-align: center;
        margin-bottom: 20px;
    }

    .file-drop-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 40vh;
    }

    .file-drop {
        border: 2px dashed #ccc;
        padding: 78px;
        text-align: center;
        cursor: pointer;
        height: 20vh;
        background-color: #f5f5f5;
        text-align: center;
        margin-bottom: 50px;
    }

    .file-drop label {
        font-size: 1.2em;
    }

    .upload-button {
        width: 25%;
        padding: 10px;
        background-color: #007BFF;
        color: white;
        border: none;
        cursor: pointer;
    }

    .file-info {
        text-align: center;
        margin-bottom: 20px;
    }

    .centered-divs {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 14vh;
    }

    .centered-text {
        text-align: center;
        padding: 0 20px;
        margin-bottom: 20px;
    }
</style>

<script>
    const fileDrop = document.querySelector('.file-drop');
    const uploadForm = document.getElementById('upload-form');
    const uploadButton = document.getElementById('upload-button');
    
    fileDrop.addEventListener('dragover', (e) => {
        e.preventDefault();
        fileDrop.classList.add('dragover');
    });

    fileDrop.addEventListener('dragleave', () => {
        fileDrop.classList.remove('dragover');
    });

    fileDrop.addEventListener('drop', (e) => {
        e.preventDefault();
        fileDrop.classList.remove('dragover');
        const file = e.dataTransfer.files[0];
        const input = document.querySelector('#id_ppi_file');
        input.files = e.dataTransfer.files;
        input.files[0] = file;
    });

    uploadForm.addEventListener('submit', (e) => {
        const inputFile = document.querySelector('#id_ppi_file');
        const fileName = inputFile.value;
        if (!fileName.endsWith('.csv') && !fileName.endsWith('.txt')) {
            e.preventDefault(); // Prevent the form from submitting
            alert('Please upload a .CSV or .TXT file.');
        }
    });
</script>
{% endblock %}